name: Default CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven
      - name: Run Tests with Maven
        run: mvn -B test

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v4
